UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/kit-12-pecas-gola-alta-chloe-cereja-marinho-branca-off-creme-nude-caqui-barro-cafe-marrom-preta-svt8r.webp' WHERE id = '2286c7ab-250e-4a05-8016-fa35c7562179'; -- Matched: Kit Sucesso 10 peças T-Shirt Neutras (Marron, Café, Cobre, Argila, Telha,Barro, Caqui, Nude, Creme, Off) -> Kit 12 Pecas Gola Alta Chloe Cereja Marinho Branca Off Creme Nude Caqui Barro Cafe Marrom Preta Svt8r
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/t-shirt-manga-longa-marinho.webp' WHERE id = 'bf0267d5-8514-4d78-b7f6-eb3771425d6b'; -- Matched: Manga Longa Marinho -> T Shirt Manga Longa Marinho
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/manga-longa-gola-alta-off-white.webp' WHERE id = 'fcf20fb3-5711-4262-a5bb-f84e67a81e67'; -- Matched: Manga Longa Off White -> Manga Longa Gola Alta Off White
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-sarah-azul-bebe.webp' WHERE id = '5384c941-0645-437f-8b71-47c15eefe99d'; -- Matched: Regata Celina Azul Bebê -> Regata Sarah Azul Bebe
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/kit-regata-sarah-da-copa-branco-off-amarelo-marinho-royal-1o0x0.webp' WHERE id = '6fdcb5a5-5a94-428a-a3fd-6a5e569268e1'; -- Matched: Kits 5 peças (Branco, Off, Amarelo, Marinho, Royal) -> Kit Regata Sarah Da Copa Branco Off Amarelo Marinho Royal 1o0x0
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/t-shirt-amarelo-da-copa-znk5r.webp' WHERE id = 'a6518c4b-7430-4f55-9e84-1cdb0cdb79a9'; -- Matched: Copa Brasil (BRA) 🇧🇷 Amarelo -> T Shirt Amarelo Da Copa Znk5r
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-sarah-branca.webp' WHERE id = 'e9c4290b-f6e1-4dca-8e45-8099b0482b8a'; -- Matched: Regata Sarah Barro -> Regata Sarah Branca
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-sarah-branca.webp' WHERE id = '13be6043-c5bf-47c6-9985-8a701c5ecfce'; -- Matched: Regata Sarah Mostarda -> Regata Sarah Branca
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-sarah-off-white.webp' WHERE id = '3ee2dc53-f1bd-42b2-973f-0f8021d55537'; -- Matched: Regata Sarah Off White -> Regata Sarah Off White
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-sarah-oliva.webp' WHERE id = 'a1b83100-49ee-471a-9244-8cc8331a905b'; -- Matched: Regata Sarah Oliva -> Regata Sarah Oliva
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/nulla-manga-azul-bebe.webp' WHERE id = '770ccdd8-a452-47c8-89d7-b5ca53279b1a'; -- Matched: Nulla Manga Azul Bebê -> Nulla Manga Azul Bebe
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-sarah-da-copa-verde-bandeira-10y8o.webp' WHERE id = '944b44b4-0d31-4145-96a2-fef7abc86c0e'; -- Matched: Copa Brasil (BRA) 🇧🇷 Bandeira -> Regata Sarah Da Copa Verde Bandeira 10y8o
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/kit-regata-sarah-da-copa-branco-off-amarelo-marinho-royal-1o0x0.webp' WHERE id = '2ff4c56b-1b55-4c35-a853-957aff2641df'; -- Matched: Kit 2 peças Copa  🇧🇷 Royal -> Kit Regata Sarah Da Copa Branco Off Amarelo Marinho Royal 1o0x0
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/vestido-de-ribana-celina-azul-jeans-jcdt1.webp' WHERE id = '1dc832f5-c50f-4dce-9dc2-d22676560cf1'; -- Matched: Vestidos Celina Jeans -> Vestido De Ribana Celina Azul Jeans Jcdt1
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-celina-nude.webp' WHERE id = '6ba52bfb-2b35-4a34-bbdd-929318babc38'; -- Matched: Vestidos Celina Nude -> Regata Celina Nude
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/t-shirt-manga-longa-argila.webp' WHERE id = 'dd03aaca-8f01-4766-a3b0-fbd027fe4596'; -- Matched: Manga Longa Argila -> T Shirt Manga Longa Argila
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/vestido-de-ribana-celina-preto-66s5b.webp' WHERE id = '9bae9971-34db-4752-87f3-1864c86ae950'; -- Matched: Vestidos Celina Preto -> Vestido De Ribana Celina Preto 66s5b
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-celina-marrom.webp' WHERE id = 'd7bbc1e6-1a80-4e5c-b6d6-a2cc5ad7c94d'; -- Matched: Vestidos Celina Marrom -> Regata Celina Marrom
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-sarah-rosa-bebe.webp' WHERE id = '182e6045-963f-4346-b85f-85152272721c'; -- Matched: Sarah Rosa Bebê -> Regata Sarah Rosa Bebe
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-sarah-branca.webp' WHERE id = 'a7e7700f-ab8e-4903-8564-44858f837ed6'; -- Matched: Regata Sarah Lilás -> Regata Sarah Branca
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-sarah-musgo.webp' WHERE id = 'f39c4cce-12e2-4151-ae6f-32eeb98b3822'; -- Matched: Regata Sarah Musgo -> Regata Sarah Musgo
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/blusa-naomi-marrom-0oh8v.webp' WHERE id = '94651002-8be8-42be-a25a-6cd559e68d9f'; -- Matched: Naomi Marrom -> Blusa Naomi Marrom 0oh8v
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-sarah-nude.webp' WHERE id = '739a4463-dad5-42d7-bfad-2e826d740acd'; -- Matched: Sarah Listrada Nude -> Regata Sarah Nude
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-sarah-da-copa-branco-1b2qf.webp' WHERE id = '708e034c-e5dd-4cab-9054-91bfa3c345e9'; -- Matched: Copa Brasil (BRA) 🇧🇷 Branco -> Regata Sarah Da Copa Branco 1b2qf
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/kit-3-t-shirt-manga-longa-off-barro-e-marron-cu69p.webp' WHERE id = '8a7da276-12a9-48d8-bbff-f9ae21b821e5'; -- Matched: Manga Longa Barro -> Kit 3 T Shirt Manga Longa Off Barro E Marron Cu69p
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-sarah-da-copa-azul-royal-1psl4.webp' WHERE id = 'ddc083bf-2db4-40d8-ab51-7d18869b65d9'; -- Matched: Sarah Copa Brasil 🇧🇷 Royal -> Regata Sarah Da Copa Azul Royal 1psl4
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/t-shirt-manga-longa-cafe.webp' WHERE id = '26b80052-b993-4b7b-a33c-b94ec148ac5b'; -- Matched: Manga Longa Café -> T Shirt Manga Longa Cafe
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/baby-t-shirt-manga-longa-caqui.webp' WHERE id = 'a73ceb5f-ac77-45f6-aade-cfdb2c352e88'; -- Matched: Manga Longa Caqui -> Baby T Shirt Manga Longa Caqui
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/t-shirts-manga-longa-mescla-gelo.webp' WHERE id = '24f819cb-a4d7-4664-8304-55647f5e5292'; -- Matched: Manga Longa Gelo -> T Shirts Manga Longa Mescla Gelo
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/t-shirt-manga-longa-nude.webp' WHERE id = '2cca028f-3867-481b-a5d7-13af00eaf7f1'; -- Matched: Manga Longa Mostarda -> T Shirt Manga Longa Nude
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/t-shirt-manga-longa-nude.webp' WHERE id = 'ea45cfb2-1d58-4fd2-99ed-590b7d948670'; -- Matched: Manga Longa Nude -> T Shirt Manga Longa Nude
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-sarah-cereja.webp' WHERE id = 'da8e405b-4774-48b3-9da0-e921570a3fd3'; -- Matched: Sarah Listrada Cereja -> Regata Sarah Cereja
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-sarah-da-copa-marinho-vuvxj.webp' WHERE id = 'a089aba3-1012-4048-a48f-112ffda1c17f'; -- Matched: Copa Brasil (BRA) 🇧🇷 Marinho -> Regata Sarah Da Copa Marinho Vuvxj
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/t-shirt-manga-longa-preta.webp' WHERE id = 'a7c19d29-e100-47ea-b6e6-34d5afdbd8c1'; -- Matched: Manga Longa Preta -> T Shirt Manga Longa Preta
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/t-shirt-off-white-da-copa-hhunl.webp' WHERE id = '38065796-9e24-4d9b-b823-76a0eb604a76'; -- Matched: Copa Brasil (BRA) 🇧🇷  Off White -> T Shirt Off White Da Copa Hhunl
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-sarah-off-white.webp' WHERE id = '80c93343-fbb2-421c-9de7-928ee9f354e7'; -- Matched: Conjunto Diana Off White -> Regata Sarah Off White
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/conj-suedine-diana-preto-l2ktr.webp' WHERE id = '5299075d-6c99-421f-b14a-ed5420f7e634'; -- Matched: Conjunto Diana Preto -> Conj Suedine Diana Preto L2ktr
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/t-shirt-marrom.webp' WHERE id = 'b6892c6e-c73d-47f0-bbab-2ca548f71885'; -- Matched: T-Shirt Marrom -> T Shirt Marrom
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-baby-sarah-preto-da-copa-187va.webp' WHERE id = '6eae0e7a-ba8c-4a3f-a756-cd7fad82fc60'; -- Matched: Copa Brasil (BRA) 🇧🇷 Preto -> Regata Baby Sarah Preto Da Copa 187va
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/t-shirt-manga-longa-preta.webp' WHERE id = '5e60189f-4992-4cff-bb93-d51078506c25'; -- Matched: Manga Longa Preta Listrada -> T Shirt Manga Longa Preta
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/t-shirt-manga-longa-cereja.webp' WHERE id = 'b20b9316-c1dd-49b2-a01b-c13c49fe2c13'; -- Matched: Manga Longa Cereja Listrada -> T Shirt Manga Longa Cereja
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/t-shirt-manga-longa-nude.webp' WHERE id = '31a85058-9000-42d9-92d5-94c66715a7fb'; -- Matched: Manga Longa Pink -> T Shirt Manga Longa Nude
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-sarah-cobre.webp' WHERE id = 'af86bc28-5ccb-4f34-8fe6-80b9fab22d5f'; -- Matched: Regata Sarah Cobre -> Regata Sarah Cobre
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-sarah-creme.webp' WHERE id = '2fd36700-714a-4b1b-92ed-0aab59ac24f6'; -- Matched: Regata Sarah Creme -> Regata Sarah Creme
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/kit-3-t-shirt-manga-longa-off-barro-e-marron-cu69p.webp' WHERE id = '3d5235fd-9389-4367-9d1d-26eaf54cb6c2'; -- Matched: Manga Longa Barro -> Kit 3 T Shirt Manga Longa Off Barro E Marron Cu69p
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/manga-longa-gola-alta-off-white.webp' WHERE id = 'dd3ffd8a-11bd-4b09-b08f-9dfb45fbeced'; -- Matched: Manga Longa Off White -> Manga Longa Gola Alta Off White
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-sarah-branca.webp' WHERE id = '42f4058d-53d6-4279-8089-d863b6b27d52'; -- Matched: Regata Sarah Maçã -> Regata Sarah Branca
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-sarah-amarelo-manteiga.webp' WHERE id = 'cf5333e8-8ace-4c88-beba-100a627cffe0'; -- Matched: Regata Sarah Manteiga -> Regata Sarah Amarelo Manteiga
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/t-shirt-azul-royal-da-copa-1yvml.webp' WHERE id = '9807c155-b8d6-4ab6-a705-61d12d50d0f6'; -- Matched: Copa Brasil (BRA) 🇧🇷 Royal -> T Shirt Azul Royal Da Copa 1yvml
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/manga-longa-gola-alta-creme.webp' WHERE id = '117e58f4-c1ea-42bc-9980-47a0fcff5bd9'; -- Matched: Manga Longa Gola alta Creme -> Manga Longa Gola Alta Creme
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/kit-5-manga-longa-gola-alta-off-nude-marrom-marinho-e-preta-1ale8.webp' WHERE id = 'e1386fb3-81a1-43cd-8bac-2c5b90e6fde0'; -- Matched: Manga Longa Gola alta Marinho -> Kit 5 Manga Longa Gola Alta Off Nude Marrom Marinho E Preta 1ale8
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/kit-5-manga-longa-gola-alta-off-nude-marrom-marinho-e-preta-1ale8.webp' WHERE id = '70604858-488e-4fd3-a1d5-2a3561bc8123'; -- Matched: Manga Longa Gola alta Marrom -> Kit 5 Manga Longa Gola Alta Off Nude Marrom Marinho E Preta 1ale8
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/manga-longa-gola-alta-nude.webp' WHERE id = '83d87553-7483-47a3-9752-f84993dfdfef'; -- Matched: Manga Longa Gola alta Nude -> Manga Longa Gola Alta Nude
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/manga-longa-gola-alta-off-white.webp' WHERE id = 'a1871be7-b6be-4af9-acb7-3457503eb1a0'; -- Matched: Manga Longa Gola alta Off White -> Manga Longa Gola Alta Off White
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/manga-longa-gola-alta-oliva.webp' WHERE id = '8691bb68-c245-4641-aa65-4f8801d8ded9'; -- Matched: Manga Longa Gola alta Oliva -> Manga Longa Gola Alta Oliva
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/kit-5-manga-longa-gola-alta-off-nude-marrom-marinho-e-preta-1ale8.webp' WHERE id = '210a39a1-9bf0-4f98-8ab5-17ca41ed6654'; -- Matched: Manga Longa Gola alta Preta -> Kit 5 Manga Longa Gola Alta Off Nude Marrom Marinho E Preta 1ale8
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-sarah-da-copa-branco-1b2qf.webp' WHERE id = '7cb3abc9-604f-4319-a135-cf69d3dfada6'; -- Matched: Copa Brasil 🇧🇷 Branco -> Regata Sarah Da Copa Branco 1b2qf
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/t-shirt-off-white-da-copa-hhunl.webp' WHERE id = '3f8734e4-8e58-4297-a00e-f6173661b694'; -- Matched: Copa Brasil 🇧🇷 Off White -> T Shirt Off White Da Copa Hhunl
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-sarah-azul-marinho.webp' WHERE id = '31ec1a76-bda4-4e04-be96-d53c0d74b9a8'; -- Matched: Regata Sarah Marinho -> Regata Sarah Azul Marinho
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/t-shirt-amarelo-da-copa-znk5r.webp' WHERE id = 'a66d8d57-8b78-4bff-a200-370afb1160cd'; -- Matched: Copa Brasil 🇧🇷 Amarelo -> T Shirt Amarelo Da Copa Znk5r
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-sarah-nude.webp' WHERE id = '848fd67b-4747-4a9b-95b6-3c1bb26576b5'; -- Matched: Regata Sarah Nude -> Regata Sarah Nude
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-sarah-azul-jeans.webp' WHERE id = '4388df2f-5b98-4fed-b652-a2255cb47108'; -- Matched: Regata Sarah Jeans -> Regata Sarah Azul Jeans
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-sarah-branca.webp' WHERE id = 'cf7425b5-b815-4f24-8eef-d93f78f96d3c'; -- Matched: Regata Sarah Céu -> Regata Sarah Branca
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-sarah-branca.webp' WHERE id = '282f81dc-06e9-4d08-bfd3-7e6e4cf2e4fe'; -- Matched: Regata Sarah Marrom -> Regata Sarah Branca
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-sarah-menta.webp' WHERE id = '057f4f4e-a46d-4d2e-8096-7fc596d1e372'; -- Matched: Regata Sarah Menta -> Regata Sarah Menta
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-sarah-cinza-mescla.webp' WHERE id = '48177c24-b911-4b24-80aa-171ed9ac957e'; -- Matched: Regata Sarah Mescla -> Regata Sarah Cinza Mescla
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-sarah-cereja.webp' WHERE id = '47ea37a6-d30e-4081-9f7e-ff3bdf733ec0'; -- Matched: Regata Sarah Cereja -> Regata Sarah Cereja
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-sarah-branca.webp' WHERE id = '31d3abab-63f6-4ee2-aa0e-da59e1084cf1'; -- Matched: Regata Sarah Chiclete -> Regata Sarah Branca
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-nulla-manga-preta.webp' WHERE id = '57dc95ed-2d82-42fe-9df8-2a3bdccb2f77'; -- Matched: Nulla Manga Preta -> Regata Nulla Manga Preta
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/t-shirt-manga-longa-marrom.webp' WHERE id = 'fc83c678-acc3-46c6-bf83-0550b7b62947'; -- Matched: Manga Longa Marrom -> T Shirt Manga Longa Marrom
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-plus-size-verde-bandeira.webp' WHERE id = 'b1daa7d3-78b9-4547-88c5-78351c2fb828'; -- Matched: Copa Plus Size 🇧🇷 Bandeira -> Regata Plus Size Verde Bandeira
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-sarah-branca.webp' WHERE id = '3f9a87aa-18c2-43ed-8988-0a2f274ddcd0'; -- Matched: Regata Sarah Pessego -> Regata Sarah Branca
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-sarah-azul-bebe.webp' WHERE id = 'd41e2c6c-5319-4a83-8f32-0d01b229fa5b'; -- Matched: Regata Sarah Azul Bebê -> Regata Sarah Azul Bebe
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-sarah-cafe.webp' WHERE id = 'f145d631-4280-481e-b881-a5f0d9209e8b'; -- Matched: Regata Sarah Café -> Regata Sarah Cafe
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/vestido-de-ribana-jade-nude.webp' WHERE id = '630023c3-db70-4d7e-9d8a-02106bacedf0'; -- Matched: Vestidos Jade Nude -> Vestido De Ribana Jade Nude
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/vestido-de-ribana-jade-marrom.webp' WHERE id = '193cba3c-1d43-444b-9814-555d1bc8ffac'; -- Matched: Vestidos Jade Marrom -> Vestido De Ribana Jade Marrom
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/vestido-de-ribana-jade-marinho.webp' WHERE id = '715f5182-4e1d-4220-9b6e-059f162ba27a'; -- Matched: Vestidos Jade Marinho -> Vestido De Ribana Jade Marinho
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/vestido-de-ribana-jade-cereja.webp' WHERE id = 'e52936ff-43b0-46b7-8c78-b767ccecdaeb'; -- Matched: Vestidos Jade Cereja -> Vestido De Ribana Jade Cereja
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/blusa-naomi-manteiga-rrexq.webp' WHERE id = '6d281faf-0bac-438f-ad7f-35c03c0bebeb'; -- Matched: Naomi Vermelha -> Blusa Naomi Manteiga Rrexq
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-sarah-off-white.webp' WHERE id = '860adb51-2faf-4dd8-bde8-cee3d988f045'; -- Matched: Sarah Listrada Off White -> Regata Sarah Off White
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/t-shirt-branca-da-copa-1v0kn.webp' WHERE id = 'ebbe9f2b-e4a0-4352-9a89-a60b1a42002f'; -- Matched: Copa Brasil 🇧🇷 Branca -> T Shirt Branca Da Copa 1v0kn
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-sarah-branca.webp' WHERE id = '7b4818f6-1ab3-4a24-aa7d-dcff819801fd'; -- Matched: Regata Sarah Grafite -> Regata Sarah Branca
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-sarah-laranja.webp' WHERE id = 'd5abfa71-2b2f-41e1-8e8f-00e50738cb2a'; -- Matched: Regata Sarah Laranja -> Regata Sarah Laranja
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-sarah-branca.webp' WHERE id = 'cabad696-6418-4dd3-bd3d-edcc6b33d2f0'; -- Matched: Regata Sarah Pêssego -> Regata Sarah Branca
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-sarah-branca.webp' WHERE id = '9fab2df5-80e5-45e9-82da-eab4cdda36f4'; -- Matched: Regata Sarah Piscina -> Regata Sarah Branca
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/conj-moletinho-rebeca-nude.webp' WHERE id = '7cf936e4-3445-44c6-9504-2e7a3684ae9a'; -- Matched: Conjunto Rebeca Nude -> Conj Moletinho Rebeca Nude
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-sarah-da-copa-marinho-vuvxj.webp' WHERE id = '818381d3-1fc6-4423-a5fd-7ed01879629c'; -- Matched: Copa Brasil 🇧🇷 Marinho -> Regata Sarah Da Copa Marinho Vuvxj
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-sarah-branca.webp' WHERE id = '882500aa-e85e-4483-8dfc-3e3df21e8d07'; -- Matched: Regata Sarah Pistache -> Regata Sarah Branca
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-sarah-branca.webp' WHERE id = '15d2cbbd-2294-4f53-be26-e3fd29b1aa26'; -- Matched: Regata Sarah Roxo -> Regata Sarah Branca
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/t-shirt-manga-longa-cereja.webp' WHERE id = '4d07e7e4-92ca-47f8-a9e3-54bbb564e5fc'; -- Matched: Manga Longa Cereja -> T Shirt Manga Longa Cereja
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/t-shirt-off-white-da-copa-hhunl.webp' WHERE id = '216c4895-c398-46a7-b44b-751dcb05362a'; -- Matched: Copa Brasil 🇧🇷 Off White -> T Shirt Off White Da Copa Hhunl
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-sarah-da-copa-verde-bandeira-10y8o.webp' WHERE id = '0e1eca22-eb53-453f-9dd8-0df185e76f22'; -- Matched: Copa Brasil 🇧🇷 Bandeira -> Regata Sarah Da Copa Verde Bandeira 10y8o
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-sarah-da-copa-azul-royal-1psl4.webp' WHERE id = 'dc6d662c-c2d9-47e4-a281-1e15cdbbb991'; -- Matched: Regata Sarah Royal -> Regata Sarah Da Copa Azul Royal 1psl4
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-sarah-branca.webp' WHERE id = 'f941f4b6-55f8-41bc-ba1b-0b739b6e2f80'; -- Matched: Regata Sarah Scarlatte -> Regata Sarah Branca
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-sarah-branca.webp' WHERE id = '5d995a1c-8797-4853-92e7-fa6025636ee7'; -- Matched: Regata Sarah Turquesa -> Regata Sarah Branca
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-sarah-vinho.webp' WHERE id = 'b1c638dd-98a9-458c-ab32-ab49e4f95abf'; -- Matched: Regata Sarah Vinho -> Regata Sarah Vinho
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-sarah-preta.webp' WHERE id = '2b4dcfca-8ef5-44d7-8bb1-de4b414526f1'; -- Matched: Sarah Listrada Preta -> Regata Sarah Preta
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-celina-rosa-bebe-1x3x8.webp' WHERE id = '85a8cc95-1cb7-492d-a9ac-7f22024d76bd'; -- Matched: Celina Rosa Bebê -> Regata Celina Rosa Bebe 1x3x8
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-luna-rosa-bebe.webp' WHERE id = '8fc91f63-35e4-4b4e-98f4-d76438c5e6c1'; -- Matched: Luna Rosa Bebê -> Regata Luna Rosa Bebe
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/t-shirt-rosa-bebe.webp' WHERE id = '275ba357-b15b-4a73-b122-345e8a90e3b7'; -- Matched: T-Shirt Rosa Bebê -> T Shirt Rosa Bebe
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/t-shirt-azul-bebe.webp' WHERE id = '107ac6dd-93da-459e-869c-2f2ac64e5c72'; -- Matched: T-shirt Azul Bebê -> T Shirt Azul Bebe
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/blusa-naomi-off-white-ysufc.webp' WHERE id = '6b21222a-cf37-465d-a716-a1d252171cf5'; -- Matched: Naomi Off White -> Blusa Naomi Off White Ysufc
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/blusa-naomi-azul-marinho-hrdga.webp' WHERE id = 'df36d1e2-09d6-41e0-a758-ea169e7ad345'; -- Matched: Naomi Marinho -> Blusa Naomi Azul Marinho Hrdga
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/blusa-naomi-manteiga-rrexq.webp' WHERE id = '2fa95bd2-8907-4912-90ad-4b84c19bd98e'; -- Matched: Naomi Manteiga -> Blusa Naomi Manteiga Rrexq
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/kit-3-t-shirt-manga-longa-off-barro-e-marron-cu69p.webp' WHERE id = 'c74a3d10-d8be-4f9d-983b-39f1827eb34b'; -- Matched: T-Shirt Barro -> Kit 3 T Shirt Manga Longa Off Barro E Marron Cu69p
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/t-shirt-branca.webp' WHERE id = 'a469f281-0de5-4a06-a629-21593b04f08b'; -- Matched: T-Shirt Branca -> T Shirt Branca
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/t-shirt-blush.webp' WHERE id = 'fba3d53d-de1b-482a-a1f9-a14af1747cc9'; -- Matched: T-Shirt Blush -> T Shirt Blush
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-sarah-cinza-mescla.webp' WHERE id = '1133c3df-c535-4c10-bc19-6ba45bb69801'; -- Matched: Sarah Listrada Mescla -> Regata Sarah Cinza Mescla
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/t-shirt-cafe.webp' WHERE id = 'd5758924-0d29-47bd-b42d-aa6e926f4b5c'; -- Matched: T-Shirt Café -> T Shirt Cafe
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-luna-preta.webp' WHERE id = 'f4f0d574-272f-4774-b86a-ef7def275de7'; -- Matched: Regata Luna Vermelha -> Regata Luna Preta
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-sarah-lavanda.webp' WHERE id = '26ea4d6b-dc50-4fdd-9765-2eae0a074f3e'; -- Matched: Regata Sarah Lavanda -> Regata Sarah Lavanda
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/t-shirt-manga-longa-verde-oliva.webp' WHERE id = 'f7dd29d2-deec-4631-b405-98b506b5b9a1'; -- Matched: Manga Longa Oliva -> T Shirt Manga Longa Verde Oliva
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/vestido-de-ribana-celina-azul-jeans-jcdt1.webp' WHERE id = '3dee42f7-679d-4b58-9f85-6bfce8c9ff5c'; -- Matched: Vestidos Celina Jeans -> Vestido De Ribana Celina Azul Jeans Jcdt1
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/t-shirt-nude.webp' WHERE id = 'c8521092-c5ec-440f-8f35-9f15161c2ad9'; -- Matched: T-shirt  Nude -> T Shirt Nude
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/t-shirt-preta-da-copa-1j1oe.webp' WHERE id = '6214fe72-3744-430c-919b-5b5697be4703'; -- Matched: Copa Brasil 🇧🇷 Preta -> T Shirt Preta Da Copa 1j1oe
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-sarah-branca.webp' WHERE id = '486ba884-59dd-4d2a-83c9-f11ade04f3d0'; -- Matched: Regata Sarah Lima -> Regata Sarah Branca
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-baby-sarah-preto-da-copa-187va.webp' WHERE id = '42fb407a-0c81-4c2a-a244-194f1eeb4dd3'; -- Matched: Sarah Preto -> Regata Baby Sarah Preto Da Copa 187va
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-sarah-branca.webp' WHERE id = '7ba38d5e-670e-4b13-a6eb-d1cb12c32687'; -- Matched: Regata Sarah Blush -> Regata Sarah Branca
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-sarah-rose.webp' WHERE id = '6344fd57-970d-4e2c-8aec-2602ae8621ea'; -- Matched: Regata Sarah Rose -> Regata Sarah Rose
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/manga-longa-gola-alta-marrrom.webp' WHERE id = 'e3ca3553-acd6-4828-a2fd-7a1aa2fce1d8'; -- Matched: Manga Longa Gola alta Barro -> Manga Longa Gola Alta Marrrom
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/t-shirt-cinza-mescla.webp' WHERE id = 'b0f62df9-7aca-45be-b2a7-66e51038e162'; -- Matched: T-Shirt Mescla -> T Shirt Cinza Mescla
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-luna-preta.webp' WHERE id = 'ef33cd96-72a8-4f29-918e-1cbcc1a43a90'; -- Matched: Regata Luna Turquesa -> Regata Luna Preta
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/t-shirt-amarelo-manteiga.webp' WHERE id = 'fdb4e891-f927-4857-ada3-7f373cb2bb84'; -- Matched: T-Shirt Manteiga -> T Shirt Amarelo Manteiga
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/t-shirt-verde-menta.webp' WHERE id = 'dc0c6cba-f9b4-49db-a864-3cbed88defb6'; -- Matched: T-Shirt Menta -> T Shirt Verde Menta
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/t-shirt-marinho.webp' WHERE id = '5dc4f8d7-f510-4b2d-bdcb-41525a5af850'; -- Matched: T-Shirt Marinho -> T Shirt Marinho
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/t-shirt-amarelo-manteiga.webp' WHERE id = '1f5eaba0-166a-4b40-bf0b-698ce666390e'; -- Matched: T-Shirt Manteiga -> T Shirt Amarelo Manteiga
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/t-shirt-preta.webp' WHERE id = '9967cd63-5b10-4d9e-8f36-f0a3dce4fdb3'; -- Matched: T-Shirt Maçã -> T Shirt Preta
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/t-shirt-preta.webp' WHERE id = '9e1467ef-ee40-4085-ad2f-455530347985'; -- Matched: T-Shirt Lima -> T Shirt Preta
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/t-shirt-preta.webp' WHERE id = '28cea344-351e-4235-8e6a-525fb8b731f9'; -- Matched: T-Shirt Lilás -> T Shirt Preta
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/t-shirt-preta.webp' WHERE id = 'b906fc4b-7d0c-4c89-b279-a6efb6f96e13'; -- Matched: T-Shirt Lavanda -> T Shirt Preta
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-sarah-da-copa-marinho-vuvxj.webp' WHERE id = '9207990e-0884-469e-805d-8f55e6c72f4e'; -- Matched: Copa Brasil 🇧🇷 Marinho -> Regata Sarah Da Copa Marinho Vuvxj
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-sarah-branca.webp' WHERE id = 'a4006d97-50de-4569-889f-a1d3b11db265'; -- Matched: Regata Sarah Telha -> Regata Sarah Branca
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-sarah-argila.webp' WHERE id = '30ce0577-281c-4846-8ccf-0ab5594519b6'; -- Matched: Regata Sarah Argila -> Regata Sarah Argila
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-sarah-verde-bandeira.webp' WHERE id = '97f72d2f-70b2-4ff6-85ad-bbe918b7e097'; -- Matched: Regata Sarah Bandeira -> Regata Sarah Verde Bandeira
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-sarah-caqui.webp' WHERE id = '74c27177-6fc0-4367-95c8-7587fdbdcffa'; -- Matched: Regata Sarah Caqui -> Regata Sarah Caqui
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-sarah-preta.webp' WHERE id = '98324a53-8554-438f-be20-79faeee79e18'; -- Matched: Regata Sarah Preta -> Regata Sarah Preta
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/t-shirt-laranja.webp' WHERE id = '9414d158-4d64-485f-81e2-da3417590e72'; -- Matched: T-Shirt Laranja -> T Shirt Laranja
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/t-shirt-creme.webp' WHERE id = '58a89f33-59d5-4470-821f-d72cb9cf985d'; -- Matched: T-Shirt Creme -> T Shirt Creme
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-sarah-branca.webp' WHERE id = '76477e92-a7fc-4d73-907d-b45bdd9e97b1'; -- Matched: Regata Sarah Barro -> Regata Sarah Branca
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/t-shirt-preta.webp' WHERE id = '89173cda-9941-46a6-898d-096019190af4'; -- Matched: T-Shirt Chiclete -> T Shirt Preta
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/t-shirt-cereja.webp' WHERE id = '96c28c12-3be5-4d07-9122-a3a5ca37acdc'; -- Matched: T-Shirt Cereja -> T Shirt Cereja
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/baby-t-shirt-preto.webp' WHERE id = '8af9efa0-1b44-41f5-ae85-1b92cdacd941'; -- Matched: T-Shirt Caqui Listrado Preto -> Baby T Shirt Preto
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/t-shirt-branca.webp' WHERE id = 'f53a4eff-88a5-4603-9b33-5b7debdcf9bb'; -- Matched: T-Shirt Branca Listrada -> T Shirt Branca
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/t-shirt-off-white-da-copa-hhunl.webp' WHERE id = '2b08cb3e-2a36-40a9-b28c-ee89d38b1830'; -- Matched: T-Shirt Off White -> T Shirt Off White Da Copa Hhunl
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/t-shirt-preta.webp' WHERE id = 'c61bf681-f879-4eca-8d07-4e9caf9eacdc'; -- Matched: T-Shirt Preta Listrada -> T Shirt Preta
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-luna-off.webp' WHERE id = 'd992441e-5e6e-494e-bec0-840b96409357'; -- Matched: Regata Luna Off -> Regata Luna Off
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/t-shirt-preta.webp' WHERE id = 'a26d3a6a-9a66-4cd0-bfb8-8e2893dc9a54'; -- Matched: T-Shirt Preta -> T Shirt Preta
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/t-shirt-preta.webp' WHERE id = 'd5e786a9-b13b-4568-84ec-5bf28745b09a'; -- Matched: T-Shirt Pistache -> T Shirt Preta
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/t-shirt-pink.webp' WHERE id = '623f4b19-d9ee-4c4f-8298-0379466c613c'; -- Matched: T-Shirt Pink -> T Shirt Pink
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/t-shirt-azul-royal.webp' WHERE id = 'adf7309a-1bd0-45f9-baa9-8478fb797dba'; -- Matched: T-Shirt Royal -> T Shirt Azul Royal
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/t-shirt-oliva.webp' WHERE id = '6c6d4094-0b55-4dd6-ae3b-6cdda0e429b6'; -- Matched: T-Shirt Oliva -> T Shirt Oliva
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/nulla-manga-cafe.webp' WHERE id = 'ad1b4e01-bce3-44f8-bc0e-28655b3dc949'; -- Matched: Nulla Manga Abóbora -> Nulla Manga Cafe
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/t-shirt-amarelo-da-copa-znk5r.webp' WHERE id = '3039672b-3ae6-42ac-8173-50e8ecd14dbe'; -- Matched: Copa Brasil 🇧🇷 Amarelo -> T Shirt Amarelo Da Copa Znk5r
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-sarah-da-copa-branco-1b2qf.webp' WHERE id = 'af9acee1-35cc-4978-8f42-fde3e967558a'; -- Matched: Regata Sarah Branco -> Regata Sarah Da Copa Branco 1b2qf
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/nulla-manga-argila.webp' WHERE id = '3a240b7f-f16b-4b59-a3d2-c49fffadb4fa'; -- Matched: Nulla Manga Argila -> Nulla Manga Argila
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/nulla-manga-azul-bebe.webp' WHERE id = 'f8a210bc-34bd-48c6-9307-af236294522b'; -- Matched: Nulla Manga Azul Céu -> Nulla Manga Azul Bebe
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/nulla-manga-blush.webp' WHERE id = '8a5f4b4d-916c-4180-b2f6-0bb0a740a6b7'; -- Matched: Nulla Manga Blush -> Nulla Manga Blush
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/nulla-manga-branca.webp' WHERE id = '69fb4de5-bfb8-4d9d-99b1-21782a681131'; -- Matched: Nulla Manga Branca -> Nulla Manga Branca
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/nulla-manga-cafe.webp' WHERE id = 'c0bc40b7-548b-49c4-9d3d-7ef8bd4c2ace'; -- Matched: Nulla Manga Café -> Nulla Manga Cafe
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/nulla-manga-cereja.webp' WHERE id = '2411586e-fe80-4a9b-8f9e-3449b880d61c'; -- Matched: Nulla Manga Cereja -> Nulla Manga Cereja
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/nulla-manga-cafe.webp' WHERE id = 'cbd63eb0-ff04-4ed5-be33-a76dbf6740a9'; -- Matched: Nulla Manga Céu -> Nulla Manga Cafe
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/nulla-manga-cafe.webp' WHERE id = '33baeb94-3427-4105-9fc3-aff8a7894499'; -- Matched: Nulla Manga Chiclete -> Nulla Manga Cafe
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-nulla-manga-royal.webp' WHERE id = '4e445a45-4f4e-4bed-b5e6-f14eebfcf6ba'; -- Matched: Nulla Manga Royal -> Regata Nulla Manga Royal
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/t-shirt-cafe.webp' WHERE id = 'bfc991e0-6040-4985-a809-e0a2062b2e11'; -- Matched: Assimétrica Café -> T Shirt Cafe
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/assimetrica-longa-caqui.webp' WHERE id = '5d40942b-60e1-4f42-b783-3d0d0883626b'; -- Matched: Assimétrica Caqui -> Assimetrica Longa Caqui
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/assimetrica-longa-cereja.webp' WHERE id = '4d51e2eb-0a54-4cdf-af7d-5dcd766818aa'; -- Matched: Assimétrica Cereja -> Assimetrica Longa Cereja
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/assimetrica-longa-creme.webp' WHERE id = 'c6f389ed-dd9a-4c19-ade2-dbcd67e70915'; -- Matched: Assimétrica Creme -> Assimetrica Longa Creme
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/assimetrica-longa-marinho.webp' WHERE id = '2840dc0e-5989-4234-b9d9-a9e90de41155'; -- Matched: Assimétrica Marinho -> Assimetrica Longa Marinho
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/t-shirt-marrom.webp' WHERE id = 'c0faa72d-d2ca-4b36-9e22-1f6a7758acd9'; -- Matched: Assimétrica Marrom -> T Shirt Marrom
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/assimetrica-longa-creme.webp' WHERE id = 'db5a863b-932c-4e13-8f74-cc936c3312d6'; -- Matched: Assimétrica Mostarda -> Assimetrica Longa Creme
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/assimetrica-longa-oliva.webp' WHERE id = '66b14d79-4c9d-4648-a684-788c1550bbdb'; -- Matched: Assimétrica Oliva -> Assimetrica Longa Oliva
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/assimetrica-longa-preta.webp' WHERE id = '4bba988e-94c1-4f9d-803d-5904de260cb9'; -- Matched: Assimétrica Preta -> Assimetrica Longa Preta
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/cropped-canelado-branco.webp' WHERE id = '47c8a976-369e-4b9f-a825-71af695b35ad'; -- Matched: Cropped Branco -> Cropped Canelado Branco
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/assimetrica-longa-off-white.webp' WHERE id = '2a92cb38-02de-40db-9086-de2367b9dab3'; -- Matched: Assimétrica Off White -> Assimetrica Longa Off White
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/cropped-canelado-nude.webp' WHERE id = '221b72d4-7836-4429-80ae-7953c795ebff'; -- Matched: Cropped Nude -> Cropped Canelado Nude
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/cropped-canelado-preto.webp' WHERE id = '3b5a9b91-8479-459c-bd84-b02666533b47'; -- Matched: Cropped Preto -> Cropped Canelado Preto
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/cropped-canelado-nude.webp' WHERE id = '7be586a1-c2b7-4043-b40a-02b456717108'; -- Matched: Cropped Telha -> Cropped Canelado Nude
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-luna-nude.webp' WHERE id = 'e1a3c3c5-3bef-416d-ab89-36bab7d0dcdf'; -- Matched: Regata Luna Nude -> Regata Luna Nude
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-luna-cinza-mescla.webp' WHERE id = '53f82529-f85f-4080-954b-feb4a409510b'; -- Matched: Regata Luna Mescla -> Regata Luna Cinza Mescla
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/nulla-manga-cafe.webp' WHERE id = 'dded9381-9ece-4c03-bdf8-9941e05aaf12'; -- Matched: Nulla Manga Barro -> Nulla Manga Cafe
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-luna-menta.webp' WHERE id = 'dae9e010-8cb2-4a6d-aa55-131b23397305'; -- Matched: Regata Luna Menta -> Regata Luna Menta
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-luna-marrom.webp' WHERE id = '33632319-16ea-47e7-bca2-372047b54081'; -- Matched: Regata Luna Marrom -> Regata Luna Marrom
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-luna-azul-marinho.webp' WHERE id = '95a041a0-b464-482e-81f5-df1e19129ee9'; -- Matched: Regata Luna Marinho -> Regata Luna Azul Marinho
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-luna-amarelo-manteiga.webp' WHERE id = 'f091eeec-0799-4993-bf48-f288308baf82'; -- Matched: Regata Luna Manteiga -> Regata Luna Amarelo Manteiga
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-luna-lavanda.webp' WHERE id = '1d250c78-860b-48a6-9c92-035427ca8471'; -- Matched: Regata Luna Lavanda -> Regata Luna Lavanda
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-luna-creme.webp' WHERE id = '2761e3e9-e955-41c7-8af4-56c2cbd5b3f6'; -- Matched: Regata Luna Creme -> Regata Luna Creme
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-luna-cereja.webp' WHERE id = '3b4e17ae-5863-4a46-9dc9-78c31ebac46f'; -- Matched: Regata Luna Cereja -> Regata Luna Cereja
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-sarah-branca.webp' WHERE id = '28cdb817-2b69-48fb-b650-92eb512a1658'; -- Matched: Regata Luna Branca -> Regata Sarah Branca
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-luna-argila.webp' WHERE id = '5c03368a-9c43-4f59-85e0-bed848b66742'; -- Matched: Regata Luna Argila -> Regata Luna Argila
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-bicolor-off-menta.webp' WHERE id = '1454a9bb-357f-45cc-90d7-4b709b80b1e0'; -- Matched: Regata Sarah Bicolor Menta com Off -> Regata Bicolor Off Menta
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-bicolor-nude-off.webp' WHERE id = '89e59cb4-dac4-421b-96e9-749e0ad4336a'; -- Matched: Regata Sarah Bicolor Nude com Off -> Regata Bicolor Nude Off
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-bicolor-nude-preto.webp' WHERE id = '951e8d28-df56-4da9-b1ee-c42d16b1d092'; -- Matched: Regata Sarah Bicolor Nude com Preto -> Regata Bicolor Nude Preto
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-bicolor-caqui-off.webp' WHERE id = '4f28103c-de07-4b7a-b107-26938c68d3a5'; -- Matched: Regata Sarah Bicolor Off com Caqui -> Regata Bicolor Caqui Off
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-bicolor-off-pink.webp' WHERE id = '8c09bb55-390b-4936-8577-5e8ae3bdf32e'; -- Matched: Regata Sarah Bicolor Pink com Barro -> Regata Bicolor Off Pink
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-bicolor-off-preto.webp' WHERE id = '03f6f8f0-cc08-4b1d-a8d2-04cb87376241'; -- Matched: Regata Sarah Bicolor Off com Preto -> Regata Bicolor Off Preto
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-bicolor-off-preto.webp' WHERE id = '6ef3f4dc-61fc-4af9-975c-d546e6405650'; -- Matched: Regata Sarah Bicolor Preto com Off -> Regata Bicolor Off Preto
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-sarah-da-copa-off-white-ug9gd.webp' WHERE id = '2b581814-b5a6-4373-85e8-f94976ebd3b1'; -- Matched: Regata Sarah Bicolor Oliva com Off -> Regata Sarah Da Copa Off White Ug9gd
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-celina-amarelo-manteiga.webp' WHERE id = 'bd996fac-458a-46b6-8d33-c002c9e9cf68'; -- Matched: Regata Celina Manteiga -> Regata Celina Amarelo Manteiga
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-nulla-manga-cobre.webp' WHERE id = 'ec95ab67-8fa0-4684-8d12-cfa5ae31107f'; -- Matched: Nulla Manga Cobre -> Regata Nulla Manga Cobre
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/nulla-manga-cafe.webp' WHERE id = 'b91c3097-7cde-40cf-9bfe-6b846bb745f0'; -- Matched: Nulla Manga Creme -> Nulla Manga Cafe
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-nulla-manga-lavanda.webp' WHERE id = 'c150c9f1-a733-4b31-aa9a-7ea7bc08b680'; -- Matched: Nulla Manga Lavanda -> Regata Nulla Manga Lavanda
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/nulla-manga-cafe.webp' WHERE id = 'e73b4f27-26f6-483a-972e-d34213363071'; -- Matched: Nulla Manga Maçã -> Nulla Manga Cafe
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/nulla-manga-manteiga.webp' WHERE id = 'd03ac220-1a3b-4578-9be6-3683ef57d893'; -- Matched: Nulla Manga Manteiga -> Nulla Manga Manteiga
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-sarah-da-copa-off-white-ug9gd.webp' WHERE id = 'e79fbc3a-9e8c-4536-b5cb-1449e8e8e2a9'; -- Matched: Regata Sarah Bicolor Off com Barro -> Regata Sarah Da Copa Off White Ug9gd
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-luna-preta.webp' WHERE id = '0e167b08-ea3d-4769-831e-55bdf7eb3dda'; -- Matched: Regata Luna Barro -> Regata Luna Preta
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-celina-barro.webp' WHERE id = 'efb8f487-b2f1-4869-a5ca-8c5d1cf0d922'; -- Matched: Regata Celina Barro -> Regata Celina Barro
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-nulla-manga-marrom.webp' WHERE id = 'cac0126e-0aae-409e-ad83-206f4382a5d9'; -- Matched: Nulla Manga Marrom -> Regata Nulla Manga Marrom
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-nulla-manga-menta.webp' WHERE id = 'c3fae66d-40ee-4c72-a347-2dabb1880849'; -- Matched: Nulla Manga Menta -> Regata Nulla Manga Menta
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/nulla-manga-cinza-mescla.webp' WHERE id = '9985f7d5-2498-41c5-a521-24dd5af089a7'; -- Matched: Nulla Manga Mescla -> Nulla Manga Cinza Mescla
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-nulla-manga-off-white.webp' WHERE id = '1feb9588-70a6-44a0-a54d-6d3d518e9b3d'; -- Matched: Nulla Manga Off White -> Regata Nulla Manga Off White
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-celina-marinho.webp' WHERE id = 'a34c5be9-b35c-4642-aa19-4f47e735c596'; -- Matched: Regata Celina Marinho -> Regata Celina Marinho
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-celina-marrom.webp' WHERE id = 'e32b729d-21b8-4b5e-b9c7-015a4a137f1c'; -- Matched: Regata Celina Marrom -> Regata Celina Marrom
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-celina-cinza-mescla.webp' WHERE id = 'f9fa169c-bb73-4e36-802d-2da8fc68364e'; -- Matched: Regata Celina Mescla -> Regata Celina Cinza Mescla
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-celina-mooca.webp' WHERE id = 'b5028c59-9ee3-4bd3-b42a-564b8d6826b0'; -- Matched: Regata Celina Mooca -> Regata Celina Mooca
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-celina-nude.webp' WHERE id = '3344a995-ca3a-418f-8e37-4025a5acc88b'; -- Matched: Regata Celina Nude -> Regata Celina Nude
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-celina-off-white.webp' WHERE id = 'fc59e622-b08c-4e78-a27c-0d2b14d77136'; -- Matched: Regata Celina Off com White -> Regata Celina Off White
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-celina-verde-oliva.webp' WHERE id = '6152b107-8290-4d10-a023-2685745155ca'; -- Matched: Regata Celina Oliva -> Regata Celina Verde Oliva
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-celina-preta.webp' WHERE id = '368093d5-e921-4e1d-99db-7a0868969623'; -- Matched: Regata Celina Preto -> Regata Celina Preta
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/gola-alta-chloe-branco.webp' WHERE id = '3f2aee89-efaf-49f2-9311-aa86202b2c31'; -- Matched: Regata Gola Alta Chloe Branco -> Gola Alta Chloe Branco
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/gola-alta-chloe-cafe.webp' WHERE id = '65a49c61-a301-4bcb-b3ae-62441888b27d'; -- Matched: Regata Gola Alta Chloe Café -> Gola Alta Chloe Cafe
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/gola-alta-chloe-caqui.webp' WHERE id = 'd107a41d-dfd0-40c6-b6b9-7deed923a5f1'; -- Matched: Regata Gola Alta Chloe Caqui -> Gola Alta Chloe Caqui
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/nulla-manga-cafe.webp' WHERE id = 'a992902d-e5b8-4aed-98b3-450db1a9f80b'; -- Matched: Nulla Manga Pêssego -> Nulla Manga Cafe
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-plus-size-preto-com-branco.webp' WHERE id = 'aedd625e-fb86-44c5-b2e6-194c5f3e4a24'; -- Matched: Regata Sarah Bicolor Branco com Preto -> Regata Plus Size Preto Com Branco
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-bicolor-caqui-off.webp' WHERE id = '1616de11-635c-4765-ace4-e33d19906064'; -- Matched: Regata Sarah Bicolor Caqui com Off -> Regata Bicolor Caqui Off
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-sarah-da-copa-off-white-ug9gd.webp' WHERE id = '3cda3584-b0a0-4482-a632-76d91205f6ee'; -- Matched: Regata Sarah Bicolor Barro com Off -> Regata Sarah Da Copa Off White Ug9gd
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-luna-azul-royal.webp' WHERE id = '6f1bac30-c494-4592-ae3f-0d49de49b3d0'; -- Matched: Regata Luna Royal -> Regata Luna Azul Royal
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-luna-preta.webp' WHERE id = 'fa2bdc1d-167c-4921-852f-d9ab191c787b'; -- Matched: Regata Luna Preta -> Regata Luna Preta
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-luna-pink.webp' WHERE id = '326344b0-4a05-464d-a5b2-5ee5a8571574'; -- Matched: Regata Luna Pink -> Regata Luna Pink
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-luna-preta.webp' WHERE id = 'ffe472df-578c-45e2-ad47-ac9e5cea1106'; -- Matched: Regata Luna Pêssego -> Regata Luna Preta
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/gola-alta-chloe-cereja.webp' WHERE id = '5789da8a-425f-4e52-8be9-f2118721fc6a'; -- Matched: Regata Gola Alta Chloe Cereja -> Gola Alta Chloe Cereja
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/gola-alta-chloe-creme.webp' WHERE id = '3fbf2c1c-877f-4286-a6c4-449ef638065b'; -- Matched: Regata Gola Alta Chloe Creme -> Gola Alta Chloe Creme
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/kit-12-pecas-gola-alta-chloe-cereja-marinho-branca-off-creme-nude-caqui-barro-cafe-marrom-preta-svt8r.webp' WHERE id = '0ade9e7c-73f9-41e9-ad6c-cd79c0d9dd5d'; -- Matched: Regata Gola Alta Chloe Barro -> Kit 12 Pecas Gola Alta Chloe Cereja Marinho Branca Off Creme Nude Caqui Barro Cafe Marrom Preta Svt8r
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/gola-alta-chloe-marinho.webp' WHERE id = 'd2cc2c87-bd08-48a9-8385-adea58e6ceec'; -- Matched: Regata Gola Alta Chloe Marinho -> Gola Alta Chloe Marinho
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/gola-alta-chloe-marrom.webp' WHERE id = '12ea807e-943e-471d-9050-797a28a0153d'; -- Matched: Regata Gola Alta Chloe Marrom -> Gola Alta Chloe Marrom
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/gola-alta-chloe-nude.webp' WHERE id = 'befb308d-a9e9-4214-9d15-cd3fc21c8214'; -- Matched: Regata Gola Alta Chloe Nude -> Gola Alta Chloe Nude
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/blusa-naomi-preto-qzqxk.webp' WHERE id = '16bcd83d-1c5e-4b1a-a631-2b58012c9f35'; -- Matched: Naomi  Preto -> Blusa Naomi Preto Qzqxk
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/gola-alta-chloe-off-white.webp' WHERE id = '69c37679-7dde-4107-b0d0-36a224486bf2'; -- Matched: Regata Gola Alta Chloe Off White -> Gola Alta Chloe Off White
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/gola-alta-chloe-preta.webp' WHERE id = '90d269f3-0e9b-45b0-a5be-75cb862fdb26'; -- Matched: Regata Gola Alta Chloe Preta -> Gola Alta Chloe Preta
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/t-shirt-preta.webp' WHERE id = 'd7ad4e9b-22b6-4005-8faf-8890c6a34421'; -- Matched: Body Preta -> T Shirt Preta
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/body-zoe-off.webp' WHERE id = 'aca1c068-de7b-4ba9-98d2-8aa08d84daac'; -- Matched: Body Off White -> Body Zoe Off
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/body-zoe-marrom.webp' WHERE id = '9e159f79-e7d4-43c8-a0b2-d882e3b4e7d7'; -- Matched: Body Marrom -> Body Zoe Marrom
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/body-zoe-marinho.webp' WHERE id = '14782c82-508a-425c-b9d8-fd67a01f1ab6'; -- Matched: Body Marinho -> Body Zoe Marinho
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/body-zoe-creme.webp' WHERE id = '00a0ae80-1895-4307-aae3-3f8b92f7e182'; -- Matched: Body Creme -> Body Zoe Creme
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/body-zoe-cereja.webp' WHERE id = '3232dbc9-09f0-457d-a7d4-75327d1b897f'; -- Matched: Body Cereja -> Body Zoe Cereja
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/t-shirt-branca.webp' WHERE id = '3689217d-15d2-46ea-b154-7347d8e7f887'; -- Matched: Body Branca -> T Shirt Branca
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/vestido-de-ribana-jade-azul-jeans.webp' WHERE id = '2b5108fe-23bc-4505-a080-fa64cd87978b'; -- Matched: Vestidos Jade Jeans -> Vestido De Ribana Jade Azul Jeans
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-sarah-off-white.webp' WHERE id = '80acafde-2aa3-4867-b07e-1298613eb46d'; -- Matched: Vestidos Jade Off White -> Regata Sarah Off White
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-sarah-branca.webp' WHERE id = 'ff63392f-7d3c-4ae9-bd46-851fdbe8e558'; -- Matched: Regata Sarah Maçã -> Regata Sarah Branca
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-sarah-laranja.webp' WHERE id = '2ad35575-d722-4831-a5ae-c37956733eca'; -- Matched: Regata Sarah Laranja -> Regata Sarah Laranja
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-sarah-creme.webp' WHERE id = '44c300e3-e688-4b8f-98f2-5f6b2518c2d3'; -- Matched: Regata Sarah Creme -> Regata Sarah Creme
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-baby-sarah-branca.webp' WHERE id = 'd70d89f0-9885-4da9-9d2d-9343b946ebcb'; -- Matched: Regata Sarah Listrada Branca -> Regata Baby Sarah Branca
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/t-shirt-oliva.webp' WHERE id = 'f7d17678-148b-4125-8b08-d3bcf8068145'; -- Matched: T-shirt Oliva -> T Shirt Oliva
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/t-shirt-nude.webp' WHERE id = '43c61709-8626-469b-9f97-499afd15aa2d'; -- Matched: T-shirt Nude -> T Shirt Nude
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-sarah-cinza-mescla.webp' WHERE id = 'e8eb8902-af88-4733-ba7d-c4ac8e6e961c'; -- Matched: Regata Sarah Mescla -> Regata Sarah Cinza Mescla
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/t-shirt-marrom.webp' WHERE id = '65d3e910-1565-41f1-bfe0-bb928ed8f0d2'; -- Matched: T-shirt Marrom -> T Shirt Marrom
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-sarah-amarelo-manteiga.webp' WHERE id = '530e1ccf-5ccb-4c92-877d-8a1e8aff39c5'; -- Matched: Regata Sarah Manteiga -> Regata Sarah Amarelo Manteiga
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-sarah-cobre.webp' WHERE id = '7d1fa3e5-73fd-4e67-a7b3-7416db21c5c3'; -- Matched: Regata Sarah Cobre -> Regata Sarah Cobre
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/t-shirt-cereja.webp' WHERE id = 'fdac2ec2-1a9d-4459-81b4-bcb0011103c9'; -- Matched: T-shirt Cereja -> T Shirt Cereja
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/t-shirt-caqui.webp' WHERE id = '4fec3f06-004c-48bf-a326-cebc1974b045'; -- Matched: T-shirt Caqui -> T Shirt Caqui
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/t-shirt-branca.webp' WHERE id = '48a736d7-bb90-4eeb-a9bc-9bcfe676de0a'; -- Matched: T-shirt Branca -> T Shirt Branca
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-plus-size-preto-com-branco.webp' WHERE id = '72dcf82b-ffca-4e8b-a470-2e3bf1d851c6'; -- Matched: Regata Sarah Preto com Branco -> Regata Plus Size Preto Com Branco
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-sarah-preta.webp' WHERE id = 'ca308ff3-1f98-4ed0-b11a-1cd47c967182'; -- Matched: Regata Sarah Preta -> Regata Sarah Preta
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/t-shirt-preta.webp' WHERE id = 'eb68c134-9635-4163-bad5-facf1e9bec35'; -- Matched: T-shirt Preta Listrada -> T Shirt Preta
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-sarah-verde-bandeira.webp' WHERE id = '20f32b1f-7549-4400-abf2-26a2311d1b02'; -- Matched: Regata Sarah Bandeira -> Regata Sarah Verde Bandeira
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/t-shirt-azul-royal.webp' WHERE id = '545bad85-3681-4825-a862-279be9f83ddf'; -- Matched: T-shirt Azul Royal -> T Shirt Azul Royal
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/t-shirt-argila.webp' WHERE id = 'fb6832c6-36aa-4a1e-8f8b-0159c4c38a92'; -- Matched: T-shirt Argila -> T Shirt Argila
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-sarah-branca.webp' WHERE id = '0dd61b9b-e8c3-4af6-8925-1712675b5f3d'; -- Matched: Regata Sarah Telha -> Regata Sarah Branca
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/t-shirt-preta.webp' WHERE id = 'f8dbba37-179a-4551-aaf1-814fd29e4465'; -- Matched: T-shirt Rose -> T Shirt Preta
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-sarah-branca.webp' WHERE id = '57805c1d-055d-4e26-a3f5-a575ae1da538'; -- Matched: Regata Sarah Piscina -> Regata Sarah Branca
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-sarah-azul-bebe.webp' WHERE id = 'fbf8c5bb-1faa-4f5b-a70a-fa4328c0fa18'; -- Matched: Regata Sarah Azul Bebê -> Regata Sarah Azul Bebe
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/kit-3-regatas-candy-color-rosa-bebe-amarelo-bebe-azul-bebe.webp' WHERE id = 'b52e8e3b-d1f5-4783-baf3-95dc4da641b8'; -- Matched: Regatas Rosa Bebê -> Kit 3 Regatas Candy Color Rosa Bebe Amarelo Bebe Azul Bebe
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/kit-luna-alcinha-3-pecas-preta-branca-jeans-1dwcf.webp' WHERE id = 'cd6378a9-202a-476d-8691-92cf7799489c'; -- Matched: Kit Verde Luna Alcinha 6 Peças -> Kit Luna Alcinha 3 Pecas Preta Branca Jeans 1dwcf
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/kit-tendencia-nulla-manga-4-pecas.webp' WHERE id = '4c14b9f4-d9a7-4ca4-be21-daa5877267ce'; -- Matched: Kit Tendência Nulla Manga 4 peças -> Kit Tendencia Nulla Manga 4 Pecas
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/kit-sarah-cores-neutras-6-pecas-marrom-barro-caqui-areia-nude-creme-xf7od.webp' WHERE id = 'be0aca9b-e4ee-487d-a5b7-0fceaca4595e'; -- Matched: Kit Palheta Cores Rosa (7 peças) pêssego, rosa bb, rose, blush, chiclete, e pink -> Kit Sarah Cores Neutras 6 Pecas Marrom Barro Caqui Areia Nude Creme Xf7od
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/kit-4-regatas-sucesso-marrom-argila-mescla-cereja-1gd4w.webp' WHERE id = 'ddeb10aa-330a-47c5-a98f-74a251f65df4'; -- Matched: Kit 4 peças Regatas Sucesso (Marrom, Argila, Fenti, Cereja) -> Kit 4 Regatas Sucesso Marrom Argila Mescla Cereja 1gd4w
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/kit-3-regatas-candy-color-rosa-bebe-amarelo-bebe-azul-bebe.webp' WHERE id = '777c6a59-7686-4ce3-8b7f-7d593db1d40a'; -- Matched: Kit 3 peças Regatas Candy Color (Rosa Bebê, Amarelo Bebê, Azul Bebê) -> Kit 3 Regatas Candy Color Rosa Bebe Amarelo Bebe Azul Bebe
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/kit-12-pecas-gola-alta-chloe-cereja-marinho-branca-off-creme-nude-caqui-barro-cafe-marrom-preta-svt8r.webp' WHERE id = '06fbf13b-9105-4161-bd66-e04a7c931569'; -- Matched: Kit 9 peças Manga Longa Gola Alta Branco, Off, Creme,Barro, Nude, Marrom, Oliva, Marinho, Preta -> Kit 12 Pecas Gola Alta Chloe Cereja Marinho Branca Off Creme Nude Caqui Barro Cafe Marrom Preta Svt8r
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/kit-12-pecas-gola-alta-chloe-cereja-marinho-branca-off-creme-nude-caqui-barro-cafe-marrom-preta-svt8r.webp' WHERE id = 'be9adfd5-d200-44db-adb9-a52838ef4915'; -- Matched: Kit 11 peças Gola alta Chloe (Barro,Cereja, Marinho, Branca, Off, Creme, Nude,Caqui, Café, Marrom, Preta) -> Kit 12 Pecas Gola Alta Chloe Cereja Marinho Branca Off Creme Nude Caqui Barro Cafe Marrom Preta Svt8r
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-baby-sarah-off.webp' WHERE id = '46dd3778-fbc9-4646-8570-025ac6f4de0e'; -- Matched: Baby Sarah Pêssego -> Regata Baby Sarah Off
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/conj-moletinho-brenda-preto.webp' WHERE id = '5b200b22-7e10-4574-a054-3f537917ac74'; -- Matched: Conjunto Brenda Preto -> Conj Moletinho Brenda Preto
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/conj-moletinho-brenda-nude.webp' WHERE id = 'ece44a39-bbb0-4cbd-b0fb-6413567a1650'; -- Matched: Conjunto Brenda Nude -> Conj Moletinho Brenda Nude
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/conj-moletinho-brenda-azul-marinho.webp' WHERE id = '66edae36-49e3-4ee6-ad92-03a0e9d5de01'; -- Matched: Conjunto Brenda Marinho -> Conj Moletinho Brenda Azul Marinho
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-baby-sarah-off.webp' WHERE id = '359c73ff-9735-418f-bfd1-779cbbd573d7'; -- Matched: Baby Sarah Piscina -> Regata Baby Sarah Off
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-baby-sarah-preta.webp' WHERE id = 'f1ed5d16-5ff7-4432-8b3e-cc2c8177acd2'; -- Matched: Baby Sarah Preta -> Regata Baby Sarah Preta
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-baby-sarah-verde.webp' WHERE id = '80ad1346-a81f-47e9-b71a-cd00a29dd670'; -- Matched: Baby Sarah Verde -> Regata Baby Sarah Verde
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-plus-size-azul-royal.webp' WHERE id = '65f33cbe-4fb8-4320-93c4-910b79af7bd2'; -- Matched: Camiseta 100% Algodão Azul Royal -> Regata Plus Size Azul Royal
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-sarah-off-white.webp' WHERE id = '6d24fd3d-cf3e-43ec-8fad-cedb39415d5c'; -- Matched: Baby Sarah Off White -> Regata Sarah Off White
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-baby-sarah-branco-da-copa-1rk5e.webp' WHERE id = '197ea85c-4de3-4faa-83d6-4cd15e46fd07'; -- Matched: Baby Sarah Branco -> Regata Baby Sarah Branco Da Copa 1rk5e
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-baby-sarah-cinza-chumbo.webp' WHERE id = 'a23f10b4-bf76-4f25-a3f6-b7e6d998b41f'; -- Matched: Baby Sarah Chumbo -> Regata Baby Sarah Cinza Chumbo
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-sarah-creme.webp' WHERE id = 'ef973c79-3b63-4f25-ac98-64526da4a4b3'; -- Matched: Baby Sarah Creme -> Regata Sarah Creme
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-baby-sarah-off.webp' WHERE id = '01ce247a-0e0e-4834-9153-60c485196ddf'; -- Matched: Baby Sarah Lilás -> Regata Baby Sarah Off
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-baby-sarah-off.webp' WHERE id = '96a664eb-d1f0-473c-a289-fb30ff3cf4c0'; -- Matched: Baby Sarah Barro -> Regata Baby Sarah Off
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/kit-regata-sarah-mae-e-filha-amarelo-da-copa-1dq4f.webp' WHERE id = '399a903f-43ec-4de1-baa2-8976dd1dbe0d'; -- Matched: Kit 2 peças Copa Brasil  🇧🇷  Amarelo -> Kit Regata Sarah Mae E Filha Amarelo Da Copa 1dq4f
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/kit-tendencia-nulla-manga-4-pecas.webp' WHERE id = 'ac2ccd5d-07f6-4983-a69b-cba1e3018b19'; -- Matched: Kit 2 peças Copa Brasil 🇧🇷 Bandeira -> Kit Tendencia Nulla Manga 4 Pecas
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/t-shirt-manga-longa-creme.webp' WHERE id = '04bcc8d2-2687-4e1d-9bc8-9cb38d63dfba'; -- Matched: Manga Longa Creme -> T Shirt Manga Longa Creme
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/kit-4-regatas-tons-candy-rosa-bebe-lavanda-manteiga-azul-bebe-9yzsb.webp' WHERE id = '1f7e6658-beef-4bd8-a289-a2d5f9b1e69d'; -- Matched: Kit 11 peças Regatas Sarah Baby Collor (Lilás, Lavanda, Azul Bebê, Piscina, Céu, Maçã, Lima, Creme, Manteiga, Rosa Bebê, Chiclete) -> Kit 4 Regatas Tons Candy Rosa Bebe Lavanda Manteiga Azul Bebe 9yzsb
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-baby-sarah-cinza-chumbo.webp' WHERE id = 'e0e04d49-23ca-4497-ab8d-79af97b864d9'; -- Matched: Regata Sarah Chumbo -> Regata Baby Sarah Cinza Chumbo
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-baby-sarah-off.webp' WHERE id = '0cbd0752-83ba-4e4b-b4b9-fb5ac932cea9'; -- Matched: Baby Sarah Maçã -> Regata Baby Sarah Off
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-baby-sarah-azul-marinho.webp' WHERE id = 'c8138943-fd3b-4a44-9f4e-6b3d7ca10da9'; -- Matched: Baby Sarah Marinho -> Regata Baby Sarah Azul Marinho
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-sarah-baby-nude.webp' WHERE id = 'ba2ccc51-5485-4e5d-b89c-4b44255b84df'; -- Matched: Baby Sarah Nude -> Regata Sarah Baby Nude
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-sarah-off-white.webp' WHERE id = '897e5ec9-87b2-4532-be99-82743af61a00'; -- Matched: Baby Sarah Off White -> Regata Sarah Off White
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-luna-baby-blue.webp' WHERE id = '4265f133-5f0c-41e9-9913-15d66e74c046'; -- Matched: Regata Luna Baby Blue -> Regata Luna Baby Blue
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/kit-3-t-shirt-manga-longa-off-barro-e-marron-cu69p.webp' WHERE id = '1f4c32a4-13de-456b-8cae-0de9bc9f3ee8'; -- Matched: T-shirt Barro -> Kit 3 T Shirt Manga Longa Off Barro E Marron Cu69p
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/t-shirt-amarelo-manteiga.webp' WHERE id = '32f5a24f-44f6-4d79-bcbe-3ba961f311f7'; -- Matched: T-shirt Manteiga -> T Shirt Amarelo Manteiga
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/t-shirt-verde-menta.webp' WHERE id = 'b52e09d3-fbcd-4b2d-8838-c27bb588c16c'; -- Matched: T-shirt Menta -> T Shirt Verde Menta
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/t-shirt-preta.webp' WHERE id = '84911911-ec0d-414d-a688-bbf9a8cf8ea3'; -- Matched: T-shirt Preta -> T Shirt Preta
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/t-shirt-azul-bebe.webp' WHERE id = '658f47d5-de28-4954-b86f-b2c60ed6f8f9'; -- Matched: T-shirt Azul Bebê -> T Shirt Azul Bebe
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/t-shirt-rosa-bebe.webp' WHERE id = '34594cd0-b49a-40d4-8a82-5eefe2a34b82'; -- Matched: T-shirt Rosa Bebê -> T Shirt Rosa Bebe
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/t-shirt-azul-bebe.webp' WHERE id = '20dce4a5-a9b1-4a06-a6f6-762043cb4cb7'; -- Matched: T-shirt Azul Bebê -> T Shirt Azul Bebe
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-baby-sarah-rosa-bebe.webp' WHERE id = 'e471330b-ed0f-4827-866c-f615c2a1bf87'; -- Matched: Baby Sarah Rosa Bebê -> Regata Baby Sarah Rosa Bebe
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-baby-sarah-preto-da-copa-187va.webp' WHERE id = '15488c46-3e48-4afe-b4b5-383173f7dfc1'; -- Matched: Copa Brasil 🇧🇷 Preto -> Regata Baby Sarah Preto Da Copa 187va
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/t-shirt-rosa-bebe.webp' WHERE id = '240c045a-07b6-46c0-8222-5c3618502b8a'; -- Matched: T-shirt Rosa Bebê -> T Shirt Rosa Bebe
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/kit-regata-sarah-mae-e-filha-marinho-da-copa-dq7cq.webp' WHERE id = 'e40bc10b-dbd3-49d5-9d64-9589f0cc45b9'; -- Matched: Kit Copa Brasil Marinho -> Kit Regata Sarah Mae E Filha Marinho Da Copa Dq7cq
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-sarah-baby-amarelo-manteiga.webp' WHERE id = '65e8bee8-2d74-4db4-a511-bdf440ac9b6e'; -- Matched: Baby Sarah Amarelo -> Regata Sarah Baby Amarelo Manteiga
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-sarah-verde-bandeira.webp' WHERE id = '50326cee-1531-40b1-9eeb-c50c7593d911'; -- Matched: Baby Sarah Bandeira -> Regata Sarah Verde Bandeira
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-baby-sarah-branco-da-copa-1rk5e.webp' WHERE id = 'e39ead43-7486-4624-8d17-aec98b457b3e'; -- Matched: Baby Sarah Branco -> Regata Baby Sarah Branco Da Copa 1rk5e
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-baby-sarah-preto-da-copa-187va.webp' WHERE id = '636723ca-556a-4955-89b8-bac56673beee'; -- Matched: Baby Sarah Preto -> Regata Baby Sarah Preto Da Copa 187va
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/regata-baby-sarah-royal-da-copa-1xhh8.webp' WHERE id = 'bc5ff87f-664f-4040-88b0-9b60d75752c7'; -- Matched: Baby Sarah Royal -> Regata Baby Sarah Royal Da Copa 1xhh8
UPDATE public.products SET image_url = 'https://fuiagxnyjiadmzayroxp.supabase.co/storage/v1/object/public/catalog/kit-tendencia-nulla-manga-4-pecas.webp' WHERE id = '7e1b0623-72c9-48a4-9832-8ac577c80e81'; -- Matched: Kit 2 peças Copa Brasil  🇧🇷 Preto -> Kit Tendencia Nulla Manga 4 Pecas